Repository akitasoftware/docker-extension, pull requests merged in 2023-04, with the labels that each got.

#40 Use "last_observed" field and polling to help the user understand extension state
  ui/src/data/queries/service.ts
  ui/src/hooks/use-akita-services.ts
  ui/src/hooks/user-akita-services.ts
  ui/src/views/agent/AgentPage.tsx
  ui/src/views/agent/components/AgentHeader.tsx
  ui/src/views/agent/components/AgentStatus.tsx
  ui/src/views/agent/components/SettingsDialog.tsx
Labels: 3 – Normal Priority, Frontend - Needs Review

#42 Eliminate need to enable visibility of Docker containers in the extension
  ui/src/data/queries/container.ts
  ui/src/hooks/use-akita-agent-container-state.ts
  ui/src/views/agent/components/AgentStatus.tsx
  ui/src/views/config/ConfigPage.tsx
  ui/src/views/config/components/SubmitWarningDialog.tsx
Labels: 2 – Blocking, Frontend - Needs Review

#43 Quick implementation of adding context to initialization failed error
  ui/src/views/agent/AgentPage.tsx
  ui/src/views/agent/components/AgentStatus.tsx
  vm/ports/router.go
Labels: 3 – Normal Priority, Frontend - Needs Review

#48 Improve Demo Stubs
  demo-server/mappings/stubs.json
  ui/src/views/agent/components/AgentHeader.tsx
  vm/infrastructure/datasource/demo-server.go
Labels: 3 – Normal Priority

#50 Add a new Analytics Event for Demo Mode
  ui/src/views/agent/AgentPage.tsx
Labels: 3 – Normal Priority, Frontend - Needs Review

#49 Fix demo request headers
  vm/infrastructure/datasource/demo-server.go
Labels: 3 – Normal Priority, Backend - Needs Review

#56 Push image automatically when a new release is published
  .github/workflows/publish.yml
  application.yml
Labels: 4 – Low Priority
